Feature#9 integration back front
BrightCoders-Institute/BCDIC22-RN-proyecto-final-team4-b pull request #10
Opened 2023-03-13 20:30 UTC by Camilapinz18

#Description
Front-end connection to backend

#What did you implemented?
-Changes realized to adapt the front-end integration
-Validators changed
-No functional code deleted

![image](https://user-images.githubusercontent.com/83082880/224824860-f0a6103a-6e99-452a-a67c-762d81e2fa68.png)
![image](https://user-images.githubusercontent.com/83082880/224825154-67d44010-5cd4-45a6-8a9e-0f220adc6637.png)

2023-03-13 23:18 UTC, yovanha requested changes

2023-03-13 23:18 UTC, yovanha commented on controllers/login.controller.js
> +  console.log("login back")
please remove your console logs

2023-03-13 23:18 UTC, yovanha commented on controllers/login.controller.js
> +  console.log(userExists,"exsisi")
same here

2023-03-13 23:18 UTC, yovanha commented on controllers/signup.controller.js
> +  )
same here

2023-03-13 23:18 UTC, yovanha commented on controllers/signup.controller.js
> +      console.log('E NOPXISTS____', alreadyExists)
same here

2023-03-14 01:02 UTC, garzo94 approved these changes

2023-03-14 20:41 UTC, yovanha approved these changes

2023-03-14 21:27 UTC, arthurchina92 approved these changes

2023-03-14 21:27 UTC, IvanGodinez21 approved these changes

2023-03-14 21:28 UTC, merged